Update Jenkins_Notes

diff --git a/Jenkins_Notes b/Jenkins_Notes
--- a/Jenkins_Notes
+++ b/Jenkins_Notes
@@ -419,6 +419,13 @@ maven stage
 [Pipeline] End of Pipeline
 Finished: SUCCESS
 
+[root@ip-172-31-92-237 ~]# jps
+12107 Jps
+3966 jenkins.war
+[root@ip-172-31-92-237 ~]# ps -aux | grep java
+jenkins   3966  1.3 19.5 3729860 785864 ?      Ssl  06:22   2:33 /etc/alternatives/java -Djava.awt.headless=true -DJENKINS_HOME=/var/lib/jenkins -jar /usr/lib/jenkins/jenkins.war --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --httpPort=8080 --debug=5 --handlerCountMax=100 --handlerCountMaxIdle=20
+root     12167  0.0  0.0 119424   964 pts/0    S+   09:26   0:00 grep --color=auto java
+
 
 
 [root@ip-172-31-92-237 opt]# cd /var/lib/jenkins/workspace/
@@ -457,4 +464,367 @@ total 92
 -rw-r--r-- 1 jenkins jenkins 1695 Nov 25 08:21 README-SSM.md
 drwxr-xr-x 3 jenkins jenkins   18 Nov 25 08:21 src
 drwxr-xr-x 6 jenkins jenkins  161 Nov 25 08:21 target
+
+
+Jenkins Pipeline to run jar on background
+
+pipeline {
+    agent any
+    tools {
+    maven 'maven-3.8.4'
+    }
+    stages{
+        stage('git checkout stage ') { 
+            steps {
+                echo 'git checkout'
+                git url:  'https://github.com/srinadhm/springboothello-CICD.git' 
+            }
+        }
+        stage('Build stage ') { 
+            steps {
+                echo 'maven stage'
+                sh 'mvn clean install' 
+            }
+        }
+        stage('run spring boot jar file  ') { 
+            steps {
+                echo 'run spring boot jar file '
+                sh "nohup java -jar target/gs-spring-boot-0.1.0.jar &"
+            }
+        }
+    }
+}
+
+Output
+
+Started by user mupparaju srinadh
+[Pipeline] Start of Pipeline
+[Pipeline] node
+Running on Jenkins in /var/lib/jenkins/workspace/Java-Pipeline-Project
+[Pipeline] {
+[Pipeline] stage
+[Pipeline] { (Declarative: Tool Install)
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] stage
+[Pipeline] { (git checkout stage )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+git checkout
+[Pipeline] git
+The recommended git tool is: NONE
+No credentials specified
+ > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/Java-Pipeline-Project/.git # timeout=10
+Fetching changes from the remote Git repository
+ > git config remote.origin.url https://github.com/srinadhm/springboothello-CICD.git # timeout=10
+Fetching upstream changes from https://github.com/srinadhm/springboothello-CICD.git
+ > git --version # timeout=10
+ > git --version # 'git version 2.32.0'
+ > git fetch --tags --force --progress -- https://github.com/srinadhm/springboothello-CICD.git +refs/heads/*:refs/remotes/origin/* # timeout=10
+ > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
+Checking out Revision af74454c512337cf4e486ee462f6ee33ab98a8b2 (refs/remotes/origin/master)
+ > git config core.sparsecheckout # timeout=10
+ > git checkout -f af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+ > git branch -a -v --no-abbrev # timeout=10
+ > git branch -D master # timeout=10
+ > git checkout -b master af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+Commit message: "Update Jenkinsfile-NexusCI"
+ > git rev-list --no-walk af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] stage
+[Pipeline] { (Build stage )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+maven stage
+[Pipeline] sh
++ mvn clean install
+[INFO] Scanning for projects...
+[INFO] 
+[INFO] -----------------< org.springframework:gs-spring-boot >-----------------
+[INFO] Building gs-spring-boot 0.1.0
+[INFO] --------------------------------[ jar ]---------------------------------
+[INFO] 
+[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ gs-spring-boot ---
+[INFO] Deleting /var/lib/jenkins/workspace/Java-Pipeline-Project/target
+[INFO] 
+[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ gs-spring-boot ---
+[INFO] Using 'UTF-8' encoding to copy filtered resources.
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/main/resources
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/main/resources
+[INFO] 
+[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ gs-spring-boot ---
+[INFO] Changes detected - recompiling the module!
+[INFO] Compiling 2 source files to /var/lib/jenkins/workspace/Java-Pipeline-Project/target/classes
+[INFO] 
+[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ gs-spring-boot ---
+[INFO] Using 'UTF-8' encoding to copy filtered resources.
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/test/resources
+[INFO] 
+[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ gs-spring-boot ---
+[INFO] No sources to compile
+[INFO] 
+[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ gs-spring-boot ---
+[INFO] No tests to run.
+[INFO] 
+[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ gs-spring-boot ---
+[INFO] Building jar: /var/lib/jenkins/workspace/Java-Pipeline-Project/target/gs-spring-boot-0.1.0.jar
+[INFO] 
+[INFO] --- spring-boot-maven-plugin:2.0.5.RELEASE:repackage (default) @ gs-spring-boot ---
+[INFO] 
+[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ gs-spring-boot ---
+[INFO] Installing /var/lib/jenkins/workspace/Java-Pipeline-Project/target/gs-spring-boot-0.1.0.jar to /var/lib/jenkins/.m2/repository/org/springframework/gs-spring-boot/0.1.0/gs-spring-boot-0.1.0.jar
+[INFO] Installing /var/lib/jenkins/workspace/Java-Pipeline-Project/pom.xml to /var/lib/jenkins/.m2/repository/org/springframework/gs-spring-boot/0.1.0/gs-spring-boot-0.1.0.pom
+[INFO] ------------------------------------------------------------------------
+[INFO] BUILD SUCCESS
+[INFO] ------------------------------------------------------------------------
+[INFO] Total time:  2.873 s
+[INFO] Finished at: 2021-11-25T09:19:32Z
+[INFO] ------------------------------------------------------------------------
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] stage
+[Pipeline] { (run spring boot jar file  ) (run spring boot jar file  )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+run spring boot jar file 
+[Pipeline] sh
++ nohup java -jar target/gs-spring-boot-0.1.0.jar
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // node
+[Pipeline] End of Pipeline
+Finished: SUCCESS
+
+
+#################
+
+Change jenkins port number:
+
+vi /etc/sysconfig/jenkins
+JENKINS_PORT="8888"
+save changes and exit
+
+service jenkins restart
+
+without nohup run the jar 
+
+pipeline {
+    agent any
+    tools {
+    maven 'maven-3.8.4'
+    }
+    stages{
+        stage('git checkout stage ') { 
+            steps {
+                echo 'git checkout'
+                git url:  'https://github.com/srinadhm/springboothello-CICD.git' 
+            }
+        }
+        stage('Build stage ') { 
+            steps {
+                echo 'maven stage'
+                sh 'mvn clean install' 
+            }
+        }
+        stage('run spring boot jar file  ') { 
+            steps {
+                echo 'run spring boot jar file '
+               sh "java -jar target/gs-spring-boot-0.1.0.jar"
+            }
+        }
+    }
+}
+
+
+[root@ip-172-31-92-237 ~]# jps
+14182 Jps
+12342 jenkins.war
+13806 gs-spring-boot-0.1.0.jar
+
+
+[root@ip-172-31-92-237 ~]# netstat -plunt | grep :8080
+tcp6       0      0 :::8080                 :::*                    LISTEN      13806/java
+
+[root@ip-172-31-92-237 ~]# curl 54.173.80.164:8080
+Greetings from Springboot..!!!
+
+
+http://54.173.80.164:8080/
+
+Greetings from Springboot..!!!
+
+Output:
+
+Started by user mupparaju srinadh
+[Pipeline] Start of Pipeline
+[Pipeline] node
+Running on Jenkins in /var/lib/jenkins/workspace/Java-Pipeline-Project
+[Pipeline] {
+[Pipeline] stage
+[Pipeline] { (Declarative: Tool Install)
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] stage
+[Pipeline] { (git checkout stage )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+git checkout
+[Pipeline] git
+The recommended git tool is: NONE
+No credentials specified
+ > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/Java-Pipeline-Project/.git # timeout=10
+Fetching changes from the remote Git repository
+ > git config remote.origin.url https://github.com/srinadhm/springboothello-CICD.git # timeout=10
+Fetching upstream changes from https://github.com/srinadhm/springboothello-CICD.git
+ > git --version # timeout=10
+ > git --version # 'git version 2.32.0'
+ > git fetch --tags --force --progress -- https://github.com/srinadhm/springboothello-CICD.git +refs/heads/*:refs/remotes/origin/* # timeout=10
+ > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
+Checking out Revision af74454c512337cf4e486ee462f6ee33ab98a8b2 (refs/remotes/origin/master)
+ > git config core.sparsecheckout # timeout=10
+ > git checkout -f af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+ > git branch -a -v --no-abbrev # timeout=10
+ > git branch -D master # timeout=10
+ > git checkout -b master af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+Commit message: "Update Jenkinsfile-NexusCI"
+ > git rev-list --no-walk af74454c512337cf4e486ee462f6ee33ab98a8b2 # timeout=10
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] stage
+[Pipeline] { (Build stage )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+maven stage
+[Pipeline] sh
++ mvn clean install
+[INFO] Scanning for projects...
+[INFO] 
+[INFO] -----------------< org.springframework:gs-spring-boot >-----------------
+[INFO] Building gs-spring-boot 0.1.0
+[INFO] --------------------------------[ jar ]---------------------------------
+[INFO] 
+[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ gs-spring-boot ---
+[INFO] Deleting /var/lib/jenkins/workspace/Java-Pipeline-Project/target
+[INFO] 
+[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ gs-spring-boot ---
+[INFO] Using 'UTF-8' encoding to copy filtered resources.
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/main/resources
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/main/resources
+[INFO] 
+[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ gs-spring-boot ---
+[INFO] Changes detected - recompiling the module!
+[INFO] Compiling 2 source files to /var/lib/jenkins/workspace/Java-Pipeline-Project/target/classes
+[INFO] 
+[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ gs-spring-boot ---
+[INFO] Using 'UTF-8' encoding to copy filtered resources.
+[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java-Pipeline-Project/src/test/resources
+[INFO] 
+[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ gs-spring-boot ---
+[INFO] No sources to compile
+[INFO] 
+[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ gs-spring-boot ---
+[INFO] No tests to run.
+[INFO] 
+[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ gs-spring-boot ---
+[INFO] Building jar: /var/lib/jenkins/workspace/Java-Pipeline-Project/target/gs-spring-boot-0.1.0.jar
+[INFO] 
+[INFO] --- spring-boot-maven-plugin:2.0.5.RELEASE:repackage (default) @ gs-spring-boot ---
+[INFO] 
+[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ gs-spring-boot ---
+[INFO] Installing /var/lib/jenkins/workspace/Java-Pipeline-Project/target/gs-spring-boot-0.1.0.jar to /var/lib/jenkins/.m2/repository/org/springframework/gs-spring-boot/0.1.0/gs-spring-boot-0.1.0.jar
+[INFO] Installing /var/lib/jenkins/workspace/Java-Pipeline-Project/pom.xml to /var/lib/jenkins/.m2/repository/org/springframework/gs-spring-boot/0.1.0/gs-spring-boot-0.1.0.pom
+[INFO] ------------------------------------------------------------------------
+[INFO] BUILD SUCCESS
+[INFO] ------------------------------------------------------------------------
+[INFO] Total time:  3.073 s
+[INFO] Finished at: 2021-11-25T09:49:06Z
+[INFO] ------------------------------------------------------------------------
+[Pipeline] }
+[Pipeline] // withEnv
+[Pipeline] }
+[Pipeline] // stage
+[Pipeline] stage
+[Pipeline] { (run spring boot jar file  ) (run spring boot jar file  )
+[Pipeline] tool
+[Pipeline] envVarsForTool
+[Pipeline] withEnv
+[Pipeline] {
+[Pipeline] echo
+run spring boot jar file 
+[Pipeline] sh
++ java -jar target/gs-spring-boot-0.1.0.jar
+
+  .   ____          _            __ _ _
+ /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
+( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
+ \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
+  '  |____| .__|_| |_|_| |_\__, | / / / /
+ =========|_|==============|___/=/_/_/_/
+ :: Spring Boot ::        (v2.0.5.RELEASE)
+
+2021-11-25 09:49:07.997  INFO 14523 --- [           main] hello.Application                        : Starting Application v0.1.0 on ip-172-31-92-237.ec2.internal with PID 14523 (/var/lib/jenkins/workspace/Java-Pipeline-Project/target/gs-spring-boot-0.1.0.jar started by jenkins in /var/lib/jenkins/workspace/Java-Pipeline-Project)
+2021-11-25 09:49:08.000  INFO 14523 --- [           main] hello.Application                        : No active profile set, falling back to default profiles: default
+2021-11-25 09:49:08.119  INFO 14523 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4c3e4790: startup date [Thu Nov 25 09:49:08 UTC 2021]; root of context hierarchy
+2021-11-25 09:49:09.735  INFO 14523 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
+2021-11-25 09:49:09.765  INFO 14523 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
+2021-11-25 09:49:09.765  INFO 14523 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.34
+2021-11-25 09:49:09.777  INFO 14523 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
+2021-11-25 09:49:09.851  INFO 14523 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
+2021-11-25 09:49:09.851  INFO 14523 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1735 ms
+2021-11-25 09:49:09.910  INFO 14523 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
+2021-11-25 09:49:09.914  INFO 14523 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
+2021-11-25 09:49:09.914  INFO 14523 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
+2021-11-25 09:49:09.915  INFO 14523 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
+2021-11-25 09:49:09.915  INFO 14523 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
+2021-11-25 09:49:10.057  INFO 14523 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
+2021-11-25 09:49:10.250  INFO 14523 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4c3e4790: startup date [Thu Nov 25 09:49:08 UTC 2021]; root of context hierarchy
+2021-11-25 09:49:10.354  INFO 14523 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/]}" onto public java.lang.String hello.HelloController.index()
+2021-11-25 09:49:10.360  INFO 14523 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
+2021-11-25 09:49:10.360  INFO 14523 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
+2021-11-25 09:49:10.396  INFO 14523 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
+2021-11-25 09:49:10.396  INFO 14523 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
+2021-11-25 09:49:10.560  INFO 14523 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
+2021-11-25 09:49:10.714  INFO 14523 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
+2021-11-25 09:49:10.721  INFO 14523 --- [           main] hello.Application                        : Started Application in 3.353 seconds (JVM running for 3.84)
+
+
+
+
+
+
 
